Repository ps-developers-sandbox/gh-im-bg-nd-230627, pull requests merged in 2023-06, with the labels that each got.

#14 Update 06-kellMorrGEA.md
  _slides/06-kellMorrGEA.md
Labels: help wanted

#11 Update 09-peolto.md
  _slides/09-peolto.md
Labels: good first issue

#12 Add caption byron infomagnus
  _slides/02-byron-infomagnus.md
  _slides/03-214001792.md
Labels: help wanted, question

#13 Comment Change - Katie Klenda
  _slides/07-kl-wells.md
Labels: help wanted
